[package]
name = "loop8"
version = "0.2.0"
description = "Eight-angle Mixamo animation exporter"
authors = ["Loop8"]
edition = "2021"

[lib]
name = "loop8_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
